### ISSUE TITLE
I made a really similar app

### ISSUE THREAD

**Issue by KraXen72** [probablykasper/vidl#7]
So i found this like 2 weeks after i finished an app that does essentially this, with a few differences: https://github.com/KraXen72/tiger  
I saw this is more robustly structured and abstracted into a cli tool, which piqued my interest.
  
- I personally think my gui for picking a thumbnail is useful but it doesen't really make sense if this app is used as a  cli tool, so that's understandable. Also i think my name is cooler 😉 but that's just preference.
1. Would you be interested in maybe merging the development of these two?
    - either on your repo (i'd pr stuff) or on my repo
2. If not, do you have any suggestions / ideas what i could improve in my app?

UDPATE: i saw that this project had numerous updates and is over 4 years old, so i guess you wouldn't want to merge on my side. If you would still like the ui for thumbnail picking PR'd and/or could give feedback that would be cool.
  
 Thanks.

**Comment by kasper9n** [comment]
Thanks for reaching out! I don't really think I'd want to have a thumbnail picker/cropper included. vidl is mainly for my personal use, and it's intentionally simple.

I might be interested in having a GUI, but I imagine that being more to customize stuff you already can do through cli, and for customizing tags - maybe as a Tauri app instead of a Python GUI. atm vidl does the job for me though, so I don't think I'd work on that anytime soon.

> do you have any suggestions / ideas what i could improve in my app?

I'll recommend you use Poetry for package management, it's quite nice
